### ISSUE TITLE
Drawings and losses

### ISSUE THREAD

**Issue by Olegui** [alfg/overwatch-api#11]
Hello!
Was the draw and defeat removed from the profile?
They were very useful to me.

Thanks!

**Comment by alfg** [comment]
Hi @pianogui, 

Losses were being calculated by `(gamesPlayed - wins)` and wasn't accounting for draws, so I removed the stat recently since it was mostly inaccurate. However, losses and draws don't seem to appear on the profile page for quickplay on https://playoverwatch.com, only competitive.

I'll look into adding losses/draws for competitive soon, but probably not quickplay unless there's another method of retrieving that stat.

Thanks!

**Comment by Olegui** [comment]
Thanks! You're great!

**Comment by alfg** [comment]
Leaving this open until I add in the fix. :)

**Comment by alfg** [comment]
`lost` and `draw` are now added to `competitive` in profile. Also note I've updated `wins` to `won` as well.

https://github.com/alfg/overwatch-api/pull/12

```json
{
    "username": "Alf",
    "games": {
        "quickplay": {
            "won": 508
        },
        "competitive": {
            "won": 26,
            "lost": 26,
            "draw": 2,
            "played": 54
        }
    },
    "playtime": {
        "quickplay": "122 hours",
        "competitive": "6 hours"
    },
    "competitive": {
        "rank": "2073",
        "rank_img": "https://blzgdapipro-a.akamaihd.net/game/rank-icons/rank-10.png"
    },
    "levelFrame": "https://blzgdapipro-a.akamaihd.net/game/playerlevelrewards/0x0250000000000928_Border.png",
    "star": "https://blzgdapipro-a.akamaihd.net/game/playerlevelrewards/0x0250000000000928_Rank.png"
}
```

Feel free to re-open if you have any issues!

Thanks!
-Alf
