### ISSUE TITLE
search suggestion

### ISSUE THREAD

**Issue by richielo** [alfg/overwatch-api#21]
I am not sure if it's possible. But is there a way to have something like a suggestion of players if I don't remember the whole battle tag? 

Another quick question, when the query is to console, is the required information still battletag? or will it be something like psn ID or xbox live username? I don't play/own a console so I am not sure. 

Thanks a lot for your help in advance

**Comment by alfg** [comment]
Hi @richielo, 

I'm not sure if the search suggestion is possible since this project is built on the existing functionality of https://playoverwatch.com. If that feature was implemented on the Overwatch website, then it may be possible.

Querying console players by Battletag ID is only supported.

Thanks!
-Alf

**Comment by richielo** [comment]
Hi @alfg 

Got it, thanks a lot for the quick reply!
