### ISSUE TITLE
Percentage of heroes use

### ISSUE THREAD

**Issue by Ande1232** [alfg/overwatch-api#22]
Hi, how can I get the percentage of heroes used? In this way I could generate bars like in playoverwatch...

I saw that in playoverwatch.com the percentage is printed in the style:
`calc(0px + 23.2266%);"`

**Comment by alfg** [comment]
Hi @Ande1232,

If using this project as your overwatch API, you would need to get the total `Time Played`, and `Top Heroes.played` values to calculate the percentage.

For example, in my stats for quickplay:

http://ow-api.herokuapp.com/stats/pc/us/Alf-1608

```json
stats.game.quickplay: [
  {
    "title": "Time Played",
    "value": "280 hours"
  },
]
```

You'll need to parse this value into an integer since it's stored as a string `"280 hours"`. Then take your top heroes and calculate it from the `played` value:

```json
stats.top_heroes.quickplay: [
  {
    "hero": "Roadhog",
    "played": "31 hours",
    "img": "https://blzgdapipro-a.akamaihd.net/game/heroes/small/0x02E0000000000040.png"
  },
]
```

You'll also need to parse this value into an integer since it's stored as a string.

So then you have:
`(31 * 100) / 280 = 11.07%`

I hope this helps!
